# Generated by Django 5.0 on 2024-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0002_expense_title_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
