# Generated by Django 5.0 on 2024-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0004_expensecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
